### ISSUE TITLE
如何获取当前URL赋值给vue的表单

### ISSUE THREAD

**Issue by liruifengv** [lavyun/Easy-todo#1]
您好，我正在写一个chrome插件，看了您的项目。我现在有个需求，是获取当前的url赋值给我的vue的input里。
我现在这样可以拿到url
我在background.js里这样写
`chrome.browserAction.onClicked.addListener((tab) => {
  alert(tab.url)
})`
但是这个动作会被弹出框popup.html覆盖，而且我怎么把这个url发给我的vue

**Comment by maixiaojie** [comment]
建议你看看浏览器插件content_script, background, popup.html之间的通讯。
